Numpy可以在硬盘中将数据以文本或者二进制文件的形式进行存入硬盘或由硬盘载入。
* np.save和np.load是高效存取硬盘数据的两大工具函数
数组在默认情况下是以未压缩的格式进行存储的，后缀名是.npy

In [2]:
import numpy as np
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('some_number',arr)

In [5]:
np.load('some_number.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 可以使用np.savez并将数组作为参数传递给该函数，用于在未压缩文件中保存多个数组

In [6]:
arr1 =np.array([3,4,5,6,7])

In [7]:
np.savez('array_archive.npz',a=arr,b=arr1)

In [8]:
arch = np.load('array_archive.npz')

In [11]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arch['b']

array([3, 4, 5, 6, 7])

In [14]:
np.savez_compressed('array_compressed.npz',a=arr,b=arr1)  # 讲多个数据压缩保存