# 4.5 线性代数
**线性代数，比如：矩阵乘法、分解、行列式等方阵数学，是所有数组类库的重要组成部分。**
在numpy中，* 是表示的是矩阵中的元素，逐元素的乘积，并不是矩阵的点乘积。因此，numpy的数组方法和numpy命名空间都有一个函数dot，用于矩阵的操作


In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y= np.array([[7,8],[8,9],[1,9]])

In [3]:
x.dot(y)

array([[ 26,  53],
       [ 74, 131]])

In [4]:
np.dot(x,y)

array([[ 26,  53],
       [ 74, 131]])

两种不同的操作方法，相同的结果。

In [5]:
x @ np.ones(3)

array([ 6., 15.])

上述 @ 特殊符号作为中缀操作符，用于点乘矩阵操作。

In [6]:
b = np.ones(3)

In [7]:
x.dot(b)

array([ 6., 15.])

## numpy.linaly
拥有一个矩阵分解的标注函数集，以及其他常用函数，例如求逆和行列式求解。
* diag 将一个方阵的对角（或非对角）元素作为一个一维数组返回，或者将一维数组转换成一个方阵，并且在非对角线上有零点。
* dot 矩阵点乘
* trace 计算对角元素和
* det 计算矩阵的行列式
* eig 计算方阵的特征值和特征向量
* inv 计算方阵的逆矩阵
* pinv 计算矩阵的Moore-Penrose 伪逆
* qr 计算QR分解
* svd 计算奇异值分解(SVD)
* solve 求解x的线性系统Ax=b ，其中A是方阵
* lstsq 计算Ax=b的最小二乘解

In [12]:
x = np.array([[3,4,5],[6,7,8],[1,9,0]])
y = np.array([[1,2,3],[4,5,6],[7,8,9],[1,9,0]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 9, 0]])

In [13]:
x

array([[3, 4, 5],
       [6, 7, 8],
       [1, 9, 0]])

In [14]:
np.diag(x)  # 取的对角线元素

array([3, 7, 0])

In [24]:
np.diag(y)  # 不是标准方阵时，也会取非对角的元素

array([1, 5, 9])

In [25]:
np.diag([0,4,8])  # 将一维数组，反构建成一个方阵，其他用0补充

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [26]:
np.trace(x)  # 计算对角元素和

10

In [27]:
np.linalg.eig(x)

(array([15.40721564, -0.70376835, -4.70344728]),
 array([[-0.43748924, -0.8201265 , -0.34007075],
        [-0.76380145,  0.04653072, -0.40560841],
        [-0.4745635 ,  0.57028714,  0.84843014]]))

# 4.6 伪随机数生成
numpy.random模块填补了python内建的random模块的不足，可以高效地生成多种概率分布下的完整样本值数组。

In [28]:
sample = np.random.normal(size=(4,4))  # 服从正态分布的4*4方阵

In [29]:
sample

array([[ 0.27973321,  0.83881879, -1.00890929,  0.94533934],
       [ 0.30211961,  0.20648886,  1.34853665,  0.54537729],
       [-0.76160765,  0.02601711, -0.09745821, -0.60758026],
       [ 0.85536419,  1.64151661, -1.10386499,  0.86768967]])

In [31]:
import random

In [34]:
a  = random.random()

In [35]:
a

0.19981448401831758

python 内建的random模块一次只能生成一个值。

numpy.random 中部分函数列表
* seed 向随机数生成器传递随机状态种子
* permutation 返回一个序列的随机排序，或者返回一个乱序的整数范围序列
* shuffle 随机排列一个序列
* rand 从均匀分布中抽取样本
* randint 根据给定的由低到高的范围抽取随机整数
* randn 从均值0方差1的正态分布中抽取样本（MATLAB型接口）
* binomial 从二项分布中抽取样本
* normal 从正态（高斯）分布中抽取样本
* beta  从beta分布中抽取样本
* chisquare 从卡方分布中抽取样本
* gamma 从伽马分布中抽取样本
* uniform 从均匀[0,1]分布中抽取样本